name: Gradle Check

on:
  workflow_call:

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - id: setup
        uses: ./.github/workflows/setup.yml

      - name: Gradle Check
        run: ./gradlew --stacktrace -PjavaVersion=${{ steps.setup.outputs.java-version }} check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
