name: Publish Gradle Plugin

on:
  create:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4

      - uses: oracle-actions/setup-java@v1
        with:
          website: ${{ vars.JDK_SRC }}
          release: ${{ vars.GRADLE_JAVA_VERSION }}

      - name: Maven Central
        run: ./gradlew check publishPluginMavenPublicationToCentralPortal -Pversion=${{ github.ref_name }} -Psign=true --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUBLISH_SECRET: ${{ secrets.GPG_PUBLISH_SECRET }}
          GPG_PUBLISH_PHRASE: ${{ secrets.GPG_PUBLISH_PHRASE }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_CENTRAL_SECRET: ${{ secrets.MAVEN_CENTRAL_SECRET }}

      - name: Github Packages
        run: ./gradlew check publish -Pversion=${{ github.ref_name }} -Psign=true --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUBLISH_SECRET: ${{ secrets.GPG_PUBLISH_SECRET }}
          GPG_PUBLISH_PHRASE: ${{ secrets.GPG_PUBLISH_PHRASE }}
