name: Publish Release

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - id: setup
        uses: sava-software/sava-build@main
        with:
          default-java-version: ${{ vars.JAVA_VERSION }}
          jdk-src: ${{ vars.JDK_SRC }}
          gradle-java-version: ${{ vars.GRADLE_JAVA_VERSION }}

      - name: Publish Packages
        id: publish
        run: |
          PROJECTS="${{ inputs.projects }}"
          PUBLISH_TASKS=""
          
          if [ -n "$PROJECTS" ]; then
            # Convert comma-delimited string to array and format each project
            IFS=',' read -ra PROJECT_ARRAY <<< "$PROJECTS"
            for project in "${PROJECT_ARRAY[@]}"; do
              # Trim whitespace
              project=$(echo "$project" | xargs)
              if [ -n "$project" ]; then
                PUBLISH_TASKS="$PUBLISH_TASKS:$project:publish "
              fi
            done
          fi
          
          ./gradlew --stacktrace -Psign=true -PjavaVersion=${{ steps.setup.outputs.java-version }} -Pversion=${{ github.ref_name }} check "$PUBLISH_TASKS" publishAggregationToCentralPortal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUBLISH_SECRET: ${{ secrets.GPG_PUBLISH_SECRET }}
          GPG_PUBLISH_PHRASE: ${{ secrets.GPG_PUBLISH_PHRASE }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_CENTRAL_SECRET: ${{ secrets.MAVEN_CENTRAL_SECRET }}
