name: Publish Release

on:
  workflow_call:
    outputs:
      java-version:
        description: "Java version"
        value: ${{ jobs.publish.outputs.java-version }}

jobs:
  publish:
    runs-on: ubuntu-latest

    outputs:
      java-version: ${{ steps.publish.outputs.java-version }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - id: setup
        uses: ./.github/workflows/setup.yml

      - name: Publish Packages
        id: publish
        run: |
          ./gradlew --stacktrace -Psign=true -PjavaVersion=${{ steps.setup.outputs.java-version }} -Pversion=${{ github.ref_name }} check publishAggregationToCentralPortal
          echo "java-version=$JAVA_VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUBLISH_SECRET: ${{ secrets.GPG_PUBLISH_SECRET }}
          GPG_PUBLISH_PHRASE: ${{ secrets.GPG_PUBLISH_PHRASE }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_CENTRAL_SECRET: ${{ secrets.MAVEN_CENTRAL_SECRET }}
