name: Publish Release

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      GPG_PUBLISH_SECRET:
        required: true
      GPG_PUBLISH_PHRASE:
        required: true
      MAVEN_CENTRAL_TOKEN:
        required: true
      MAVEN_CENTRAL_SECRET:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - id: setup
        uses: ./.github/workflows/setup.yml

      - name: Publish Packages
        run: |
          ./gradlew --stacktrace -Psign=true -PjavaVersion=${{ steps.setup.outputs.java-version }} -Pversion=${{ github.ref_name }} check publishAggregationToCentralPortal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PUBLISH_SECRET: ${{ secrets.GPG_PUBLISH_SECRET }}
          GPG_PUBLISH_PHRASE: ${{ secrets.GPG_PUBLISH_PHRASE }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_CENTRAL_SECRET: ${{ secrets.MAVEN_CENTRAL_SECRET }}
